<mxfile host="app.diagrams.net"><diagram name="Netflix Architecture - Viva"><mxGraphModel grid="1" gridSize="10" pageWidth="1200" pageHeight="900"><root><mxCell id="0"/><mxCell id="1" parent="0"/>
<mxCell id="u" value="USER&#xa;Mobile / TV / Browser" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;fontSize=16;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="60" y="250" width="180" height="70" as="geometry"/></mxCell>
<mxCell id="d" value="DNS" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#fff2cc;strokeColor=#d6b656;fontSize=16;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="300" y="250" width="150" height="70" as="geometry"/></mxCell>
<mxCell id="l" value="LOAD BALANCER" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#f8cecc;strokeColor=#b85450;fontSize=16;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="510" y="250" width="190" height="70" as="geometry"/></mxCell>
<mxCell id="b" value="NETFLIX BACKEND&#xa;&#xa;👤 User Service&#xa;🎬 Movie / Catalog Service&#xa;🔎 Search Service&#xa;⭐ Recommendation Service&#xa;▶ Playback Service" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#d5e8d4;strokeColor=#82b366;fontSize=15;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="760" y="110" width="300" height="330" as="geometry"/></mxCell>
<mxCell id="db" value="DATABASE&#xa;Users • Movies • Watch History" style="shape=cylinder;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;fontSize=14;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="760" y="510" width="210" height="100" as="geometry"/></mxCell>
<mxCell id="c" value="CACHE&#xa;Frequently accessed data" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#fff2cc;strokeColor=#d6b656;fontSize=14;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="1010" y="510" width="210" height="100" as="geometry"/></mxCell>
<mxCell id="vs" value="VIDEO STORAGE&#xa;Actual movie / episode files" style="shape=cylinder;whiteSpace=wrap;html=1;fillColor=#f8cecc;strokeColor=#b85450;fontSize=14;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="250" y="700" width="220" height="100" as="geometry"/></mxCell>
<mxCell id="cdn" value="CDN&#xa;Delivers video &amp; images" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#e1d5e7;strokeColor=#9673a6;fontSize=15;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="550" y="700" width="220" height="100" as="geometry"/></mxCell>
<mxCell id="wu" value="USER&#xa;Receives video / thumbnails" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;fontSize=15;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="850" y="700" width="220" height="100" as="geometry"/></mxCell>
<mxCell id="e1" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="u" target="d"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e2" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="d" target="l"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e3" value="Requests" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="l" target="b"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e4" value="Read / Write" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="b" target="db"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e5" value="Fast access" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="b" target="c"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e6" value="Video" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="vs" target="cdn"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e7" value="Video / thumbnails" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="cdn" target="wu"><mxGeometry relative="1" as="geometry"/></mxCell>
<mxCell id="e8" value="Playback" style="edgeStyle=orthogonalEdgeStyle;endArrow=block;" edge="1" parent="1" source="b" target="vs"><mxGeometry relative="1" as="geometry"/></mxCell>
</root></mxGraphModel></diagram></mxfile>
